$ANSIBLE_VAULT;1.1;AES256
66653361643936396232383361633139626337336639363561643333383634643835323865653537
3763356135326632633533363735373966376336323462310a363035306366336433383230313239
61666635643634393038653732316433376663333666613638303233393337393230663033323666
6662323734366365330a656136653461306665646337616261343062373961626466353361663630
38376466326162666636383566383763336261343838656232663963643538633535363233623436
64333836343766646130343238643763666636356464323966623035323739343034336465376534
33643831376263333764326136323438313632643139336163333761633036353066343533373231
39386236396637666139363963323930306536636461346462353531613766623365353730663130
66383964646632386339363362643562353266323931643566313337633731616263373933653761
37353330656564656139356530363662363232313936613930303864626235316537396333633737
306161366363383263323337393436383039
